shape: 차원의 수 확인   
axis: 기준이 되는 축 (0, 1, 2 ...)

## 1. Numpy : 과학적 계산해줌

In [1]:
import numpy as np

In [2]:
np

<module 'numpy' from '/usr/local/lib/python3.6/dist-packages/numpy/__init__.py'>

## 2. ndarray 생성하기

In [3]:
arr = np.array([1,2,3,4], dtype=int)


In [4]:
arr

array([1, 2, 3, 4])

In [6]:
[1, 2, 3, 4] #list랑 조금 다름

[1, 2, 3, 4]

In [7]:
type(arr)

numpy.ndarray

### 2-1. list로부터 생성하기

In [8]:
mylist1 = [1, 2, 3, 4] #1차원 리스트

In [9]:
mylist2 = [[1, 2, 3, 4], #2차원 리스트, 대괄호 두번!!
           [5, 6, 7, 8]]

In [10]:
arr1 = np.array(mylist1)


In [11]:
arr2 = np.array(mylist2)


### 2-2. shape확인하기  
shape: 차원의 수를 확인


In [13]:
arr1.shape #1차원의 개수 4


(4,)

In [14]:
arr2.shape #행 2 열 4


(2, 4)

## 3. array에서의 data 타입

array에서는 list와는 다르게 1개의 **단일 데이터 타입**만 허용.

### 3-1. list에서의 data 타입

In [33]:
mylist = [1, 3.14, '정민', '1234']

In [34]:
mylist

[1, 3.14, '정민', '1234']

In [35]:
mylist[1]


3.14

In [36]:
mylist[2]

'정민'

### 3-2. array에서의 data 타입 (case를 통한 연구)

### case 1. int와 float 타입이 혼재된 경우

In [37]:
arr = np.array([1, 2, 3, 3.14])

In [38]:
arr #정수가 실수에 맞춰서 바뀜

array([1.  , 2.  , 3.  , 3.14])

### case 2. int와 float 타입이 혼재되었으나, dtype을 지정한 경우

In [39]:
arr = np.array([1, 2, 3, 3.14], dtype=int)

In [40]:
arr #실수가 정수에 맞춤(따로 설정해줬을 때)

array([1, 2, 3, 3])

### case 3. int와 str 타입이 혼재된 경우

In [41]:
arr = np.array([1, 3.14, '정민', '1234'])

In [42]:
arr #정수와 실수가 문자열로 바뀜

array(['1', '3.14', '정민', '1234'], dtype='<U32')

In [43]:
arr[0] + arr[1] #문자열이기 때문에 앞뒤를 붙임

'13.14'

### case 4. int와 str 타입이 혼재되어 있고 int로 dtype을 지정한 경우

In [44]:
arr = np.array([1, 3.14, '정민','1234'], dtype=int) #문자열은 도저히 실수로 못 바꿈

ValueError: ignored

In [45]:
arr

array(['1', '3.14', '정민', '1234'], dtype='<U32')