In [2]:
import numpy as np

## 1. 슬라이싱 (Slicing)

배열의 부분 선택

In [3]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr.shape

(10,)

### 1-1. index 지정하여 색인

#### 1차원 array

In [5]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr[0]

0

In [7]:
arr[-1]

9

#### 2차원 array: 순서 주의

In [8]:
arr2d = np.array([[1, 2, 3, 4], 
                  [5, 6, 7, 8], 
                  [9, 10, 11, 12]])

In [9]:
arr2d.shape

(3, 4)

arr2d[행, 열]

In [10]:
arr2d[0,2]

3

### 1-2. 범위 색인

#### 1차원

index 1**이상** 끝까지

In [ ]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
arr[1:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

index 5 **미만** 까지

In [12]:
arr[:5]

array([0, 1, 2, 3, 4])

index 1이상 5미만

In [13]:
arr[1:5]

array([1, 2, 3, 4])

#### 2차원

In [14]:
arr2d = np.array([[1, 2, 3, 4], 
                  [5, 6, 7, 8], 
                  [9, 10, 11, 12]])

row(행)을 모두 가져오려는 경우

In [17]:
arr2d[0, :] 

array([1, 2, 3, 4])

column(열)을 모두 가져오려는 경우

In [18]:
arr2d[: ,2]

array([ 3,  7, 11])

부분 적으로 가져오려는 경우

In [19]:
arr2d[:2, :]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [20]:
arr2d[:2, 2:]

array([[3, 4],
       [7, 8]])

## 2. Fancy 인덱싱

fancy 인덱싱은 범위가 아닌 **특정 index의 집합의 값을 선택하여 추출**하고 싶을 때

In [21]:
arr = np.array([10, 23, 2, 7, 90, 65, 32, 66, 70])

반드시 **[추출하고 싶은 인덱스]** 꺾쇠 괄호로 묶어 주세요

In [22]:
arr[[1,3,5]]

array([23,  7, 65])

변수에 지정 후 추출도 가능

In [23]:
# 코드를 입력해 주세요
idx = [1,3,5]

In [24]:
arr[idx]

array([23,  7, 65])

### 2-2. 2차원 array

In [25]:
arr2d = np.array([[1, 2, 3, 4], 
                  [5, 6, 7, 8], 
                  [9, 10, 11, 12]])

In [26]:
arr2d[[0,1],:]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [29]:
arr2d[:2,:]  #이렇게 해도 됨

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [30]:
arr2d[:,1:]

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12]])

In [32]:
arr2d[:,[1,2,3]] #이렇게 해도 됨

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12]])

## 3. Boolean 인덱싱

조건 필터링을 통하여 Boolean 값을 이용한 색인

In [33]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

In [34]:
arr2d = np.array([[1, 2, 3, 4], 
                  [5, 6, 7, 8], 
                  [9, 10, 11, 12]])

### 3-1. True와 False 값으로 색인하기

In [35]:
myTrueFalse = [True, False, True]

In [37]:
arr[myTrueFalse] #개수가 일치하지 않아 오류

IndexError: ignored

In [38]:
myTrueFalse = [True, False, True, True, False, False, True]

In [39]:
arr[myTrueFalse]

array([1, 3, 4, 7])

### boolean indexing 어떻게 활용될 수 있나?  

어떤 조건을 주고 그 조건에 만족하는 것들만 색인하고 싶을 때 활용

### 3-2. 조건필터

조건 연산자를 활용

In [41]:
arr2d > 2 #2이상인 것 가져오고 싶을 때


array([[False, False,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

필터를 활용하여 필터에 True 조건만 색인 

이럴 때 꺾쇠 괄호로 한 번 더 묶어주기 (꺾쇠 괄호 안에 조건문 삽입) 

arr2d[**조건필터**]

In [ ]:
arr2d = np.array([[1, 2, 3, 4], 
                  [5, 6, 7, 8], 
                  [9, 10, 11, 12]])

In [42]:
arr2d[arr2d>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [43]:
arr2d[arr2d < 5]

array([1, 2, 3, 4])