In [1]:
import numpy as np

# Matrix

중요한 이유: 엑셀 시트의 매출액 합하는 등 연산할 때

## 1. 행렬 - 덧셈

- shape이 같아야 함
- 같은 position끼리 연산

### 1-1. 덧셈

In [4]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [5]:
b = np.array([[3, 4, 5], 
              [1, 2, 3]])

In [6]:
a+b

array([[4, 6, 8],
       [3, 5, 7]])

In [7]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [8]:
b = np.array([[1, 2],
              [3, 4],  
              [5, 6]])

In [10]:
a + b #shape이 같아야 함!

ValueError: ignored

### 1-2. Sum

In [11]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [13]:
np.sum(a, axis=0)

array([3, 5, 7])

In [15]:
np.sum(a, axis=1)

array([6, 9])

## 2. 행렬 - 뺄셈

In [16]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [17]:
b = np.array([[3, 4, 5], 
              [1, 2, 3]])

In [18]:
a-b

array([[-2, -2, -2],
       [ 1,  1,  1]])

In [19]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [20]:
b = np.array([[1, 2],
              [3, 4],  
              [5, 6]])

## 3. 곱셈

- 맞닿는 shape이 같아야함

일반 곱셈: 같은 position에 있는 값끼리 곱하기 (영업이익끼리, ...)

In [22]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [23]:
b = np.array([[3, 4, 5], 
              [1, 2, 3]])

In [24]:
a.shape, b.shape

((2, 3), (2, 3))

In [25]:
a*b

array([[ 3,  8, 15],
       [ 2,  6, 12]])

단순 곱셈과 dot product는 다름: 맞닿는 shape이 동일할 때

In [30]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [31]:
b = np.array([[3, 4, 5], 
              [1, 2, 3]])

In [32]:
a * b

array([[ 3,  8, 15],
       [ 2,  6, 12]])

In [33]:
a = np.array([[1, 2, 3],
              [1, 2, 3], 
              [2, 3, 4]])

In [34]:
b = np.array([[1, 2],
              [3, 4],  
              [5, 6]])

In [35]:
a.shape, b.shape

((3, 3), (3, 2))

In [36]:
np.dot(a,b)

array([[22, 28],
       [22, 28],
       [31, 40]])