In [1]:
import numpy as np

## 1. Broadcasting

예) 전체적으로 100을 더하고 싶을 때 등

## 1-1. 숫자의 연산 (단일)

In [2]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [3]:
b = np.array([[3, 3, 3], 
              [3, 3, 3]])

In [4]:
a + b #복잡하고 귀찮음

array([[4, 5, 6],
       [5, 6, 7]])

In [5]:
a +3

array([[4, 5, 6],
       [5, 6, 7]])

In [6]:
a-3

array([[-2, -1,  0],
       [-1,  0,  1]])

In [7]:
a*3

array([[ 3,  6,  9],
       [ 6,  9, 12]])

In [8]:
a/3

array([[0.33333333, 0.66666667, 1.        ],
       [0.66666667, 1.        , 1.33333333]])