In [1]:
import numpy as np

## 1. arange란?

arange와 range를 같이 공부

**[실제 상황 예시]**

우리는 순차적인 값을 생성할 때가 많음.

1. 회원에 대한 가입 번호 부여 (1번 회원부터 순차적으로~)
2. 100개 한정 판매 상품에 대한 고유 번호 부여

등등.. 이 밖에도 데이터 관리를 위한 인덱스를 차례대로 부여하는 것은 매우 흔함

### 1-1. 순서대로 리스트에 값을 생성하려면?

1~10까지 값을 생성하려면?

In [24]:
arr = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [25]:
arr

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

### 1-2. arange를 사용해서 쉽게 생성하기

첫번째 인자에는 **start 이상**, 두번째 인자에는 **stop의 미만** 

In [26]:
arr = np.arange(1,11)


In [27]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## 1-3. keyword 인자를 사용해보기

keyword 인자는 파라미터(인자)의 keyword를 지정해줌으로썬 순서 없이 지정 가능

In [28]:
arr = np.arange(start=1, stop=11)
#왜 굳이? 1) 복잡한 함수일 때 직관적 이해 가능

In [29]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
arr = np.arange(stop=11, start=1)
# 2) 순서가 바뀌어도 상관 없음.

In [31]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### 1-4. 홀수의 값만 생성

**step 키워드 활용**

In [32]:
arr = np.arange(1,11,2)

In [33]:
arr

array([1, 3, 5, 7, 9])

In [34]:
arr = np.arange(start=1, stop=11, step=2)

In [35]:
arr

array([1, 3, 5, 7, 9])

## 2. range (numpy와는 상관없는 python 문법)

* range는 말 그대로 범위를 지정  
* 보통 for in 의 반복문에서 주로 사용.

In [36]:
arr = np.arange(1,11)

In [37]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
for i in arr:
    print(i)

1
2
3
4
5
6
7
8
9
10


### 2-1. range 구문 활용시

In [39]:
for i in range(1, 11):
    print(i)

1
2
3
4
5
6
7
8
9
10


In [40]:
for i in range(1, 11, 2):
    print(i)

1
3
5
7
9
